apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: \${METADATA_NAME}
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/startupProbe
        value:
          httpGet:
            path: /healthz/startup
            port: 8080
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          httpGet:
            path: /healthz/ready
            port: 8080
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe
        value:
          httpGet:
            path: /healthz/live
            port: 8080
      - op: add
        path: /spec/template/spec/containers/0/ports
        value:
          - containerPort: 8080
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ASPNETCORE_URLS
          value: "http://*:8080"