apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: StatefulSet
      name: \${METADATA_NAME}
    patch: |-
      - op: add
        path: /spec/template/spec/volumes
        value:
          - name: mssql-persistent-storage
            hostPath:
              path: ${PWD}/localSetup/database/mssql/data
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value:
          - name: mssql-persistent-storage
            mountPath: /var/opt/mssql
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            value: "yourStrong(!)Password"
      - op: add
        path: /spec/template/spec/containers/0/ports
        value:
          - containerPort: 1433
  - target:
      kind: Service
      name: \${METADATA_NAME}
    patch: |-
      - op: add
        path: /spec/ports
        value:
          - name: mssql
            port: 31433
            targetPort: 1433
            nodePort: 31433