apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: \${METADATA_NAME}
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/startupProbe
        value:
          grpc:
            service: greet.Greeter
            port: 5001
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          grpc:
            service: greet.Greeter
            port: 5001
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe
        value:
          grpc:
            port: 5001
      - op: add
        path: /spec/template/spec/containers/0/ports
        value:
          - containerPort: 5001
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ASPNETCORE_URLS
          value: "http://*:5001"