apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${METADATA_NAME}
spec:
  selector:
    matchLabels:
      app: PATCH_BY_KUSTOMIZE
  template:
    spec:
      containers:
        - name: ${CONTAINER_NAME}
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: ${ASPNETCORE_ENVIRONMENT}
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
              
